### ISSUE TITLE
第三回のロゴをつくる

### ISSUE THREAD

**Issue by denari** [kosen10s/lt03docs#3]

**Comment by pndcat** [comment]
それさ、早めに作ってくれると嬉しいな♡
（実際ブログ書こうと思った時にないじゃーーーーんってなった

**Comment by denari** [comment]
![lt 3](https://cloud.githubusercontent.com/assets/5387939/12118299/050f2504-b409-11e5-8e23-1be0900e8272.png)
![lt 3wide](https://cloud.githubusercontent.com/assets/5387939/12118298/050e16aa-b409-11e5-90d6-277731626b83.png)

**Comment by ysakasin** [comment]
`#3`の下部に謎のドットが……

**Comment by pndcat** [comment]
なんか3の上にもドットない？？
