### ISSUE TITLE
懇親会

### ISSUE THREAD

**Issue by denari** [kosen10s/lt03docs#4]
またうなすけくんを召喚するか迷う

**Comment by unasuke** [comment]
ref https://github.com/kosen10s/lt02docs/issues/9

**Comment by unasuke** [comment]
https://kosen10s.doorkeeper.jp/events/36741

現参加者18名 + 懇親会だけ参加できる1名(すずよし)

20人で予約取れば良さそう？

**Comment by denari** [comment]
@unasuke よいです〜

**Comment by unasuke** [comment]
:ok_woman:

**Comment by unasuke** [comment]
test

**Comment by unasuke** [comment]
[白木屋 渋谷道玄坂店 - 渋谷/居酒屋 [食べログ]](http://tabelog.com/tokyo/A1303/A130301/13051857/)

ここで18時から20人「中村」で予約

**Comment by unasuke** [comment]
20人、多い

**Comment by unasuke** [comment]
食べ終わったら閉じる

**Comment by unasuke** [comment]
ごちそうさまでした
