### ISSUE TITLE
ステッカー

### ISSUE THREAD

**Issue by denari** [kosen10s/lt03docs#6]
次こそ作ろう。マジで。そろそろ欲しい

**Comment by denari** [comment]
@unasuke 福井雪エグいし、届く気がしないのでs社に送っていいですか!?ありがとうございます!!!!!!

**Comment by unasuke** [comment]
@denari アッウッス

**Comment by unasuke** [comment]
@denari 宛名は僕でお願いします(当然か)

**Comment by denari** [comment]
@unasuke 順当に行けば、金曜に届きます。お楽しみに。

**Comment by unasuke** [comment]
おーけーうーまん
